# 使用的配置文件
spring:
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
        time-between-eviction-runs:

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#加密
jasypt:
  encryptor:
    bean: encryptorBean


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#redis
jedisCluster:
  nodes: 106.12.150.214
  poolConfig:
    max-Total: 20
    max-idle: 8
    min-idle: 1
    max-wait-millis: 1500
  connectionTimeOut: 1000
  soTimeOut: 1000
  maxAttempt: 5
  password:

#zk
curator:
  #重试次数
  retryCount: 5
  #重试间隔时间
  elapsedTimeMs: 5000
  #zookeeper 地址
  connectString: 106.12.150.214:2181
  #session超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000