# 使用的配置文件
spring:
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        max-active:
        max-idle:
        max-wait:
        min-idle:
        time-between-eviction-runs:

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#加密
jasypt:
  encryptor:
    bean: encryptorBean


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#redis
jedisCluster:
  nodes: 106.12.150.214
  poolConfig:
    max-Total: 20
    max-idle: 8
    min-idle: 1
    max-wait-millis: 1500
  connectionTimeOut: 1000
  soTimeOut: 1000
  maxAttempt: 5
  password: ysg0x1joart2
