# 使用的配置文件
spring:
  profiles:
    active: dev

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#加密
jasypt:
  encryptor:
    bean: encryptorBean


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50